name: tests
on:
  workflow_dispatch:
  push:
  pull_request:
  
jobs:
  tests:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Code Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: npm ci
        run: npm ci

      - name: Code Lint
        run: npm run lint

      - name: Runing tests
        run: npm test

  
